---
- name: "Find oc"
  hosts: workshop
  tasks:
    - name: check openshift log in
      command: >-
        oc whoami
      ignore_errors: no
      register: oc_whoami
    
- name: "Install API Workshop"
  hosts: workshop
  roles:
    - workshop
