---
- name: "Uninstall"
  hosts: workshop
  tasks:
  - name: Delete gogs project
    shell: "oc delete project {{ gogs_project }}"
    register: output
    failed_when: output.stderr != '' and 'not found' not in output.stderr and 'The system is ensuring all content is removed from this namespace.' not in output.stderr
    changed_when: output.rc == 0

  - name: Delete Microcks project
    shell: "oc delete project {{ microcks_project }}"
    register: output
    failed_when: output.stderr != '' and 'not found' not in output.stderr and 'The system is ensuring all content is removed from this namespace.' not in output.stderr
    changed_when: output.rc == 0

  - name: Delete APICurio project
    shell: "oc delete project {{ apicurio_project }}"
    register: output
    failed_when: output.stderr != '' and 'not found' not in output.stderr and 'The system is ensuring all content is removed from this namespace.' not in output.stderr
    changed_when: output.rc == 0

  - name: Delete SSO project
    shell: "oc delete project {{ sso_project }}"
    register: output
    failed_when: output.stderr != '' and 'not found' not in output.stderr and 'The system is ensuring all content is removed from this namespace.' not in output.stderr
    changed_when: output.rc == 0

  - name: Delete 3scale project
    shell: "oc delete project {{ threescale_project }}"
    register: output
    failed_when: output.stderr != '' and 'not found' not in output.stderr and 'The system is ensuring all content is removed from this namespace.' not in output.stderr
    changed_when: output.rc == 0