---
- name: Make sure we go back to default project
  shell: "oc project default"

- name: Create the 3scale app
  shell: "oc new-app -f https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/master/amp/amp.yml \
  --param WILDCARD_DOMAIN={{ ocp_apps_domain }} --param ADMIN_PASSWORD=password --param WILDCARD_POLICY=Subdomain \
  --param ADMIN_ACCESS_TOKEN={{threescale_admin_access_token}} --param MASTER_PASSWORD=password \  
  --param MASTER_ACCESS_TOKEN={{threescale_master_access_token}} -n {{ namespace }}"
  when: configure_only == 'false'
  register: command_result
  failed_when: "command_result.rc != 0 and 'already exists' not in command_result.stderr"  

- name: Delete RWX storage as RWO (hack)
  shell: "oc -n {{ namespace }} delete pvc/system-storage"
  when: command_result.rc == 0
  failed_when: command_result.stderr != '' and 'not found' not in command_result

- template:
    src: storage.yml.j2
    dest: /tmp/storage.yml
  when: command_result.rc == 0

- name: Create RWO (hack)
  shell: oc create -f /tmp/storage.yml -n {{ namespace }}
  when: command_result.rc == 0  

- name: Wait until 3scale API is available 
  uri: 
    url: https://master.{{ ocp_apps_domain }}
    method: HEAD
    validate_certs: no
  register: wait_threescale_result
  until: wait_threescale_result is succeeded
  ignore_errors: yes
  retries: 30
  delay: 60

#- include_tasks: create-wildcard-route.yml
#  when: create_wildcard_route == 'true'

- name: Make sure we go back to default project
  shell: "oc project default"
